[project]
name = "llmfs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "notebook>=7.5.3",
    "pandas>=3.0.0",
    "tiktoken>=0.12.0",
    "torch>=2.10.0",
]
